# Generated by Django 6.0.2 on 2026-02-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalakriti', '0004_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
