# Generated by Django 6.0.2 on 2026-02-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalakriti', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
