# Generated by Django 6.0.2 on 2026-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalakriti', '0007_add_seller_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='region',
        ),
        migrations.AlterField(
            model_name='seller',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
