# Generated by Django 6.0.2 on 2026-02-18 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalakriti', '0008_remove_seller_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentioned_artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in_posts', to='kalakriti.artisan')),
                ('mentioned_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in_posts', to='kalakriti.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='storypost',
            index=models.Index(fields=['-created_at'], name='kalakriti_s_created_2b2fea_idx'),
        ),
        migrations.AddIndex(
            model_name='storypost',
            index=models.Index(fields=['user', '-created_at'], name='kalakriti_s_user_id_34c369_idx'),
        ),
    ]
